# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20181221_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
