# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
