# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20181221_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galley Image', 'verbose_name_plural': 'Gallery Images'},
        ),
    ]
