# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20181221_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='gallery_info',
            field=models.TextField(default='aaaaaaa'),
            preserve_default=False,
        ),
    ]
