# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_about_socialmediaprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.URLField(),
        ),
    ]
